"""Initial schema: every table from docs/architecture/02-data-model.md.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-15 11:21:24+00:00

Autogenerated against SQLite, then reviewed by hand:
- generic SQLAlchemy types only (PostgreSQL 16+ and SQLite);
- enums are VARCHAR(32) + CHECK (``native_enum=False``); enum values are frozen here, not imported;
- CHECK/unique/index/FK names come from ``op.f()`` or the naming convention of
  ``app.models.base`` (alembic/env.py passes ``target_metadata``);
- server defaults are portable (``true``/``false``, ``now()``);
- downgrade drops tables in reverse dependency order (indexes go with their tables).
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

USER_ROLE = ("ADMIN", "OPERATOR")
LANGUAGE = ("ru", "tg")
ORDER_STATUS = (
    "NEW",
    "WAITING_CONFIRMATION",
    "CONFIRMED",
    "PREPARING",
    "READY",
    "HANDED_TO_COURIER",
    "COMPLETED",
    "CANCELLED",
)
PAYMENT_STATUS = ("UNPAID", "PARTIALLY_PAID", "PAID", "REFUNDED")
DELIVERY_TYPE = ("DELIVERY", "PICKUP")
PAYMENT_METHOD = ("CASH", "CARD", "TRANSFER", "OTHER")
PAYMENT_KIND = ("PAYMENT", "REFUND")
ORDER_SOURCE = ("INSTAGRAM", "ADMIN")
ACTOR_TYPE = ("USER", "CUSTOMER", "AI", "SYSTEM")
CONVERSATION_MODE = ("AI", "HUMAN_HANDOFF")
MESSAGE_DIRECTION = ("INCOMING", "OUTGOING")
MESSAGE_TYPE = ("TEXT", "VOICE", "IMAGE", "SYSTEM")
MESSAGE_SENDER = ("CUSTOMER", "AI", "OPERATOR", "SYSTEM")
MESSAGE_DELIVERY_STATUS = ("PENDING", "SENT", "FAILED", "NOT_APPLICABLE")
GEOCODE_STATUS = ("PENDING", "OK", "NOT_FOUND", "AMBIGUOUS", "FAILED", "MANUAL")
LOCATION_SOURCE = ("CUSTOMER_PIN", "GEOCODER", "OPERATOR", "COURIER")
DELIVERY_STATUS = ("PENDING", "AWAITING_DISPATCH", "DISPATCHED", "DELIVERED", "FAILED", "CANCELLED")
DISPATCH_PROVIDER = ("MAXIM_MANUAL", "MAXIM_API")

TABLES_IN_CREATION_ORDER = (
    "users",
    "customers",
    "products",
    "faq_items",
    "daily_reports",
    "app_settings",
    "refresh_tokens",
    "conversations",
    "messages",
    "orders",
    "order_items",
    "order_events",
    "payments",
    "deliveries",
    "location_requests",
    "route_plans",
    "route_stops",
)


def _enum(name: str, values: tuple[str, ...]) -> sa.Enum:
    return sa.Enum(*values, name=name, native_enum=False, create_constraint=True, length=32)


def _money() -> sa.Numeric:
    return sa.Numeric(precision=12, scale=2)


def _coordinate() -> sa.Numeric:
    return sa.Numeric(precision=9, scale=6)


def _created_at() -> sa.Column:
    return sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)


def _updated_at() -> sa.Column:
    return sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)


def _true() -> sa.TextClause:
    return sa.text("true")


def _false() -> sa.TextClause:
    return sa.text("false")


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=128), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", _enum("role", USER_ROLE), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=_true(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        _created_at(),
        _updated_at(),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )

    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instagram_user_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("language", _enum("language", LANGUAGE), server_default="ru", nullable=False),
        sa.Column("is_new", sa.Boolean(), server_default=_true(), nullable=False),
        sa.Column("last_order_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        _created_at(),
        _updated_at(),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("instagram_user_id", name=op.f("uq_customers_instagram_user_id")),
    )
    op.create_index(op.f("ix_customers_phone"), "customers", ["phone"], unique=False)

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", _money(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="TJS", nullable=False),
        sa.Column("unit", sa.String(length=16), server_default="шт.", nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=_true(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        _created_at(),
        _updated_at(),
        sa.CheckConstraint("price > 0", name=op.f("ck_products_price_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )

    op.create_table(
        "faq_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("question_tg", sa.Text(), nullable=True),
        sa.Column("answer_tg", sa.Text(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=_true(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        _created_at(),
        _updated_at(),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faq_items")),
    )

    op.create_table(
        "daily_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        _created_at(),
        _updated_at(),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_reports")),
        sa.UniqueConstraint("report_date", name=op.f("uq_daily_reports_report_date")),
    )

    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        _created_at(),
        _updated_at(),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_app_settings_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_settings")),
    )

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        _created_at(),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("jti", name=op.f("uq_refresh_tokens_jti")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("instagram_conversation_id", sa.String(length=128), nullable=True),
        sa.Column("mode", _enum("mode", CONVERSATION_MODE), server_default="AI", nullable=False),
        sa.Column("handoff_reason", sa.Text(), nullable=True),
        sa.Column("handoff_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("needs_attention", sa.Boolean(), server_default=_false(), nullable=False),
        sa.Column("assigned_user_id", sa.Integer(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_customer_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("failed_ai_attempts", sa.Integer(), server_default="0", nullable=False),
        _created_at(),
        _updated_at(),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
            name=op.f("fk_conversations_assigned_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_conversations_customer_id_customers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("instagram_conversation_id", name=op.f("uq_conversations_instagram_conversation_id")),
    )
    op.create_index(op.f("ix_conversations_customer_id"), "conversations", ["customer_id"], unique=False)
    op.create_index(op.f("ix_conversations_last_message_at"), "conversations", ["last_message_at"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("direction", _enum("direction", MESSAGE_DIRECTION), nullable=False),
        sa.Column("message_type", _enum("message_type", MESSAGE_TYPE), nullable=False),
        sa.Column("sender", _enum("sender", MESSAGE_SENDER), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("audio_url", sa.Text(), nullable=True),
        sa.Column("media_url", sa.Text(), nullable=True),
        sa.Column("instagram_message_id", sa.String(length=255), nullable=True),
        sa.Column("ai_processed", sa.Boolean(), server_default=_false(), nullable=False),
        sa.Column("intent", sa.String(length=32), nullable=True),
        sa.Column("ai_payload", sa.JSON(none_as_null=True), nullable=True),
        sa.Column(
            "delivery_status",
            _enum("delivery_status", MESSAGE_DELIVERY_STATUS),
            server_default="NOT_APPLICABLE",
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sent_by_user_id", sa.Integer(), nullable=True),
        _created_at(),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sent_by_user_id"], ["users.id"], name=op.f("fk_messages_sent_by_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("instagram_message_id", name=op.f("uq_messages_instagram_message_id")),
    )
    op.create_index(op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False)
    op.create_index(
        "ix_messages_conversation_id_created_at", "messages", ["conversation_id", "created_at"], unique=False
    )

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("source", _enum("source", ORDER_SOURCE), nullable=False),
        sa.Column("status", _enum("status", ORDER_STATUS), server_default="NEW", nullable=False),
        sa.Column("payment_status", _enum("payment_status", PAYMENT_STATUS), server_default="UNPAID", nullable=False),
        sa.Column("payment_method", _enum("payment_method", PAYMENT_METHOD), nullable=True),
        sa.Column("delivery_type", _enum("delivery_type", DELIVERY_TYPE), nullable=True),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column("delivery_latitude", _coordinate(), nullable=True),
        sa.Column("delivery_longitude", _coordinate(), nullable=True),
        sa.Column("delivery_date", sa.Date(), nullable=True),
        sa.Column("delivery_time", sa.Time(), nullable=True),
        sa.Column("total_amount", _money(), server_default="0", nullable=False),
        sa.Column("paid_amount", _money(), server_default="0", nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("is_repeat_customer", sa.Boolean(), server_default=_false(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        _created_at(),
        _updated_at(),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_orders_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], name=op.f("fk_orders_customer_id_customers")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_delivery_date"), "orders", ["delivery_date"], unique=False)
    op.create_index("ix_orders_delivery_date_status", "orders", ["delivery_date", "status"], unique=False)
    op.create_index("ix_orders_customer_id_status", "orders", ["customer_id", "status"], unique=False)

    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("product_name", sa.String(length=128), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", _money(), nullable=False),
        sa.Column("total_price", _money(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        _created_at(),
        _updated_at(),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_order_items_product_id_products"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)

    op.create_table(
        "order_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("actor_type", _enum("actor_type", ACTOR_TYPE), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        _created_at(),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_order_events_actor_user_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_events_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_events")),
    )
    op.create_index(op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False)

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("kind", _enum("kind", PAYMENT_KIND), nullable=False),
        sa.Column("amount", _money(), nullable=False),
        sa.Column("method", _enum("method", PAYMENT_METHOD), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        _created_at(),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_payments_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_payments_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)

    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("address_raw", sa.Text(), nullable=False),
        sa.Column("address_formatted", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=64), server_default="Худжанд", nullable=False),
        sa.Column("district", sa.String(length=64), nullable=True),
        sa.Column("microdistrict", sa.String(length=32), nullable=True),
        sa.Column("street", sa.String(length=128), nullable=True),
        sa.Column("house", sa.String(length=32), nullable=True),
        sa.Column("apartment", sa.String(length=16), nullable=True),
        sa.Column("entrance", sa.String(length=16), nullable=True),
        sa.Column("floor", sa.String(length=8), nullable=True),
        sa.Column("landmark", sa.Text(), nullable=True),
        sa.Column("latitude", _coordinate(), nullable=True),
        sa.Column("longitude", _coordinate(), nullable=True),
        sa.Column("location_source", _enum("location_source", LOCATION_SOURCE), nullable=True),
        sa.Column("geocode_status", _enum("geocode_status", GEOCODE_STATUS), server_default="PENDING", nullable=False),
        sa.Column("geocode_provider", sa.String(length=32), nullable=True),
        sa.Column("geocode_candidates", sa.JSON(), nullable=False),
        sa.Column("recipient_name", sa.String(length=128), nullable=True),
        sa.Column("recipient_phone", sa.String(length=32), nullable=True),
        sa.Column("courier_comment", sa.Text(), nullable=True),
        sa.Column("status", _enum("status", DELIVERY_STATUS), server_default="PENDING", nullable=False),
        sa.Column("dispatch_provider", _enum("dispatch_provider", DISPATCH_PROVIDER), nullable=True),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("external_status", sa.String(length=64), nullable=True),
        sa.Column("courier_name", sa.String(length=128), nullable=True),
        sa.Column("courier_phone", sa.String(length=32), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        _created_at(),
        _updated_at(),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_deliveries_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint("order_id", name=op.f("uq_deliveries_order_id")),
    )

    op.create_table(
        "location_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("delivery_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latitude", _coordinate(), nullable=True),
        sa.Column("longitude", _coordinate(), nullable=True),
        _created_at(),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_location_requests_delivery_id_deliveries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location_requests")),
        sa.UniqueConstraint("token", name=op.f("uq_location_requests_token")),
    )
    op.create_index(op.f("ix_location_requests_delivery_id"), "location_requests", ["delivery_id"], unique=False)

    op.create_table(
        "route_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column("start_name", sa.String(length=128), nullable=False),
        sa.Column("start_latitude", _coordinate(), nullable=False),
        sa.Column("start_longitude", _coordinate(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("algorithm", sa.String(length=32), nullable=False),
        sa.Column("distance_source", sa.String(length=32), nullable=False),
        sa.Column("total_distance_m", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_duration_s", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        _created_at(),
        _updated_at(),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_route_plans_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_plans")),
    )
    op.create_index(op.f("ix_route_plans_delivery_date"), "route_plans", ["delivery_date"], unique=False)

    op.create_table(
        "route_stops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_plan_id", sa.Integer(), nullable=False),
        sa.Column("delivery_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("eta", sa.Time(), nullable=True),
        sa.Column("distance_from_prev_m", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_from_prev_s", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lateness_min", sa.Integer(), server_default="0", nullable=False),
        _created_at(),
        _updated_at(),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_route_stops_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_route_stops_delivery_id_deliveries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["route_plan_id"],
            ["route_plans.id"],
            name=op.f("fk_route_stops_route_plan_id_route_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_stops")),
    )
    op.create_index(op.f("ix_route_stops_route_plan_id"), "route_stops", ["route_plan_id"], unique=False)
    op.create_index(op.f("ix_route_stops_delivery_id"), "route_stops", ["delivery_id"], unique=False)


def downgrade() -> None:
    for table_name in reversed(TABLES_IN_CREATION_ORDER):
        op.drop_table(table_name)
